<a href="https://colab.research.google.com/github/IrartemI/New/blob/main/main1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list = [3, 5, 1, 6]
sorted(my_list)

[1, 3, 5, 6]

Это я пробую какую-то новую хрень

In [ ]:
import tensorflow as tf
x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [ ]:
import tensorflow as tf
x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [ ]:
import tensorflow as tf
x = tf.random.normal(shape=(3,1), mean=0., stddev=1.)
print(x)

tf.Tensor(
[[0.4765539 ]
 [1.4149132 ]
 [0.37624133]], shape=(3, 1), dtype=float32)


In [ ]:
import numpy as np
x = np.ones(shape=(2, 2))
x[0,0] = 0
print(x)

[[0. 1.]
 [1. 1.]]


In [ ]:
import tensorflow as tf
a = tf.ones((2, 2))
print(a)
b = tf.square(a)
print(b)
c = tf.sqrt(a)
print (c)
d = b + c
print(d)
e = tf.matmul(a, b)
e *= d

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float32)
